<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Komal Nagaraj">
<meta name="dcterms.date" content="2025-04-23">

<title>A Replication of Karlan and List (2007) – Komal’s Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Komal’s Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data">Data</a>
  <ul class="collapse">
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description">Description</a></li>
  <li><a href="#balance-test" id="toc-balance-test" class="nav-link" data-scroll-target="#balance-test">Balance Test</a></li>
  </ul></li>
  <li><a href="#experimental-results" id="toc-experimental-results" class="nav-link" data-scroll-target="#experimental-results">Experimental Results</a>
  <ul class="collapse">
  <li><a href="#charitable-contribution-made" id="toc-charitable-contribution-made" class="nav-link" data-scroll-target="#charitable-contribution-made">Charitable Contribution Made</a></li>
  <li><a href="#differences-between-match-rates" id="toc-differences-between-match-rates" class="nav-link" data-scroll-target="#differences-between-match-rates">Differences between Match Rates</a></li>
  <li><a href="#size-of-charitable-contribution" id="toc-size-of-charitable-contribution" class="nav-link" data-scroll-target="#size-of-charitable-contribution">Size of Charitable Contribution</a></li>
  </ul></li>
  <li><a href="#simulation-experiment" id="toc-simulation-experiment" class="nav-link" data-scroll-target="#simulation-experiment">Simulation Experiment</a>
  <ul class="collapse">
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers">Law of Large Numbers</a></li>
  <li><a href="#central-limit-theorem" id="toc-central-limit-theorem" class="nav-link" data-scroll-target="#central-limit-theorem">Central Limit Theorem</a></li>
  <li><a href="#central-limit-theorem-simulation" id="toc-central-limit-theorem-simulation" class="nav-link" data-scroll-target="#central-limit-theorem-simulation">Central Limit Theorem: Simulation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">A Replication of Karlan and List (2007)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Komal Nagaraj </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 23, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Dean Karlan at Yale and John List at the University of Chicago conducted a field experiment to test the effectiveness of different fundraising letters. They sent out 50,000 fundraising letters to potential donors, randomly assigning each letter to one of three treatments: a standard letter, a matching grant letter, or a challenge grant letter. They published the results of this experiment in the <em>American Economic Review</em> in 2007. The article and supporting data are available from the <a href="https://www.aeaweb.org/articles?id=10.1257/aer.97.5.1774">AEA website</a> and from Innovations for Poverty Action as part of <a href="https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27853&amp;version=4.2">Harvard’s Dataverse</a>. Giving USA shows that in the United States, charitable gifts of money have been 2 percent or more of GDP since 1998, and more than 89 percent of Americans donate to charity. In order to understand the economics of charity, this field experiment was conducted to understand up to what extent the ‘price’ matters in a charitable fundraising using a mail solicitation. In other words the main aim of this experiment was to understand, can offering a matching grant (where a donation is “matched” by another donor) influence whether people give to charity—and how much they give?</p>
<p>The following experimental setup was used for the study:</p>
<p>A large-scale field experiment was done with over 50,000 previous donors to a real liberal political charity in the U.S. The donors were randomly split into two groups: - Control group (no mention of a match) - Treatment group (offered a matching grant—e.g., if you donate $1, another $1, $2, or $3 is added)</p>
<p>Within the treatment group, three factors were varied: - Match ratio: $1:$1, $2:$1, or $3:$1 - Maximum match amount: $25,000, $50,000, $100,000, or unstated - Suggested donation amount: based on past giving (same as before, or slightly higher)</p>
<p>This project seeks to replicate their results.</p>
</section>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<section id="description" class="level3">
<h3 class="anchored" data-anchor-id="description">Description</h3>
<p>To conduct this experiment 50,083 donors were chosen and different statistics were collected for this experiment. Individuals were randomly assigned to either a control group or a matching grant treatment group, and within the matching grant treatment group individuals were randomly assigned to different matching grant rates,matching grant maximum amounts, and suggested donation amounts.The collected data had the following information for each donor:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Variable Definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 75%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>treatment</code></td>
<td>Treatment</td>
</tr>
<tr class="even">
<td><code>control</code></td>
<td>Control</td>
</tr>
<tr class="odd">
<td><code>ratio</code></td>
<td>Match ratio</td>
</tr>
<tr class="even">
<td><code>ratio2</code></td>
<td>2:1 match ratio</td>
</tr>
<tr class="odd">
<td><code>ratio3</code></td>
<td>3:1 match ratio</td>
</tr>
<tr class="even">
<td><code>size</code></td>
<td>Match threshold</td>
</tr>
<tr class="odd">
<td><code>size25</code></td>
<td>$25,000 match threshold</td>
</tr>
<tr class="even">
<td><code>size50</code></td>
<td>$50,000 match threshold</td>
</tr>
<tr class="odd">
<td><code>size100</code></td>
<td>$100,000 match threshold</td>
</tr>
<tr class="even">
<td><code>sizeno</code></td>
<td>Unstated match threshold</td>
</tr>
<tr class="odd">
<td><code>ask</code></td>
<td>Suggested donation amount</td>
</tr>
<tr class="even">
<td><code>askd1</code></td>
<td>Suggested donation was highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>askd2</code></td>
<td>Suggested donation was 1.25 x highest previous contribution</td>
</tr>
<tr class="even">
<td><code>askd3</code></td>
<td>Suggested donation was 1.50 x highest previous contribution</td>
</tr>
<tr class="odd">
<td><code>ask1</code></td>
<td>Highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>ask2</code></td>
<td>1.25 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="odd">
<td><code>ask3</code></td>
<td>1.50 x highest previous contribution (for suggestion)</td>
</tr>
<tr class="even">
<td><code>amount</code></td>
<td>Dollars given</td>
</tr>
<tr class="odd">
<td><code>gave</code></td>
<td>Gave anything</td>
</tr>
<tr class="even">
<td><code>amountchange</code></td>
<td>Change in amount given</td>
</tr>
<tr class="odd">
<td><code>hpa</code></td>
<td>Highest previous contribution</td>
</tr>
<tr class="even">
<td><code>ltmedmra</code></td>
<td>Small prior donor: last gift was less than median $35</td>
</tr>
<tr class="odd">
<td><code>freq</code></td>
<td>Number of prior donations</td>
</tr>
<tr class="even">
<td><code>years</code></td>
<td>Number of years since initial donation</td>
</tr>
<tr class="odd">
<td><code>year5</code></td>
<td>At least 5 years since initial donation</td>
</tr>
<tr class="even">
<td><code>mrm2</code></td>
<td>Number of months since last donation</td>
</tr>
<tr class="odd">
<td><code>dormant</code></td>
<td>Already donated in 2005</td>
</tr>
<tr class="even">
<td><code>female</code></td>
<td>Female</td>
</tr>
<tr class="odd">
<td><code>couple</code></td>
<td>Couple</td>
</tr>
<tr class="even">
<td><code>state50one</code></td>
<td>State tag: 1 for one observation of each of 50 states; 0 otherwise</td>
</tr>
<tr class="odd">
<td><code>nonlit</code></td>
<td>Nonlitigation</td>
</tr>
<tr class="even">
<td><code>cases</code></td>
<td>Court cases from state in 2004-5 in which organization was involved</td>
</tr>
<tr class="odd">
<td><code>statecnt</code></td>
<td>Percent of sample from state</td>
</tr>
<tr class="even">
<td><code>stateresponse</code></td>
<td>Proportion of sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponset</code></td>
<td>Proportion of treated sample from the state who gave</td>
</tr>
<tr class="even">
<td><code>stateresponsec</code></td>
<td>Proportion of control sample from the state who gave</td>
</tr>
<tr class="odd">
<td><code>stateresponsetminc</code></td>
<td>stateresponset - stateresponsec</td>
</tr>
<tr class="even">
<td><code>perbush</code></td>
<td>State vote share for Bush</td>
</tr>
<tr class="odd">
<td><code>close25</code></td>
<td>State vote share for Bush between 47.5% and 52.5%</td>
</tr>
<tr class="even">
<td><code>red0</code></td>
<td>Red state</td>
</tr>
<tr class="odd">
<td><code>blue0</code></td>
<td>Blue state</td>
</tr>
<tr class="even">
<td><code>redcty</code></td>
<td>Red county</td>
</tr>
<tr class="odd">
<td><code>bluecty</code></td>
<td>Blue county</td>
</tr>
<tr class="even">
<td><code>pwhite</code></td>
<td>Proportion white within zip code</td>
</tr>
<tr class="odd">
<td><code>pblack</code></td>
<td>Proportion black within zip code</td>
</tr>
<tr class="even">
<td><code>page18_39</code></td>
<td>Proportion age 18-39 within zip code</td>
</tr>
<tr class="odd">
<td><code>ave_hh_sz</code></td>
<td>Average household size within zip code</td>
</tr>
<tr class="even">
<td><code>median_hhincome</code></td>
<td>Median household income within zip code</td>
</tr>
<tr class="odd">
<td><code>powner</code></td>
<td>Proportion house owner within zip code</td>
</tr>
<tr class="even">
<td><code>psch_atlstba</code></td>
<td>Proportion who finished college within zip code</td>
</tr>
<tr class="odd">
<td><code>pop_propurban</code></td>
<td>Proportion of population urban within zip code</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The following table describes the categorical data with the number of rows populated (Count), number of unique values in that particular field (unique), the most common value for a field (Top), and the number of occurrences of the top value (frequency).</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Categorical Data Summary
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Count</th>
<th>Unique</th>
<th>Top</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>treatment</td>
<td>50083</td>
<td>2</td>
<td>1</td>
<td>33396</td>
</tr>
<tr class="even">
<td>control</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>33396</td>
</tr>
<tr class="odd">
<td>ratio</td>
<td>50083</td>
<td>4</td>
<td>Control</td>
<td>16687</td>
</tr>
<tr class="even">
<td>ratio2</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>38949</td>
</tr>
<tr class="odd">
<td>ratio3</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>38954</td>
</tr>
<tr class="even">
<td>size</td>
<td>50083</td>
<td>5</td>
<td>Control</td>
<td>16687</td>
</tr>
<tr class="odd">
<td>size25</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>41733</td>
</tr>
<tr class="even">
<td>size50</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>41738</td>
</tr>
<tr class="odd">
<td>size100</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>41733</td>
</tr>
<tr class="even">
<td>sizeno</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>41732</td>
</tr>
<tr class="odd">
<td>ask</td>
<td>50083</td>
<td>4</td>
<td>Control</td>
<td>16687</td>
</tr>
<tr class="even">
<td>askd1</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>38949</td>
</tr>
<tr class="odd">
<td>askd2</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>38950</td>
</tr>
<tr class="even">
<td>askd3</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>38954</td>
</tr>
<tr class="odd">
<td>gave</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>49049</td>
</tr>
<tr class="even">
<td>ltmedmra</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>25356</td>
</tr>
<tr class="odd">
<td>year5</td>
<td>50083</td>
<td>2</td>
<td>1</td>
<td>25483</td>
</tr>
<tr class="even">
<td>dormant</td>
<td>50083</td>
<td>2</td>
<td>1</td>
<td>26217</td>
</tr>
<tr class="odd">
<td>state50one</td>
<td>50083</td>
<td>2</td>
<td>0</td>
<td>50033</td>
</tr>
<tr class="even">
<td>red0</td>
<td>50048</td>
<td>2</td>
<td>0</td>
<td>29806</td>
</tr>
<tr class="odd">
<td>blue0</td>
<td>50048</td>
<td>2</td>
<td>1</td>
<td>29806</td>
</tr>
<tr class="even">
<td>redcty</td>
<td>49978</td>
<td>2</td>
<td>1</td>
<td>25501</td>
</tr>
<tr class="odd">
<td>bluecty</td>
<td>49978</td>
<td>2</td>
<td>0</td>
<td>25553</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The following tables have the number of rows populated for a field (Count), Mean value of the field (Mean), Standard deviation of the field (Std Dev), Minimum value of the field (Min), Maximum value of the field (Max) and 25, 50 and 75 percentile of the values for the field.</p>
<p>Summary description on Numerical Variables:</p>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Donation and Donor Variables Summary
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Count</th>
<th>Mean</th>
<th>Std Dev</th>
<th>Min</th>
<th>25%</th>
<th>50%</th>
<th>75%</th>
<th>Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ask1</td>
<td>50083</td>
<td>71.50</td>
<td>101.73</td>
<td>25.00</td>
<td>35.00</td>
<td>45.00</td>
<td>65.00</td>
<td>1500.00</td>
</tr>
<tr class="even">
<td>ask2</td>
<td>50083</td>
<td>91.79</td>
<td>127.25</td>
<td>35.00</td>
<td>45.00</td>
<td>60.00</td>
<td>85.00</td>
<td>1875.00</td>
</tr>
<tr class="odd">
<td>ask3</td>
<td>50083</td>
<td>111.05</td>
<td>151.67</td>
<td>50.00</td>
<td>55.00</td>
<td>70.00</td>
<td>100.00</td>
<td>2250.00</td>
</tr>
<tr class="even">
<td>amount</td>
<td>50083</td>
<td>0.92</td>
<td>8.71</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>400.00</td>
</tr>
<tr class="odd">
<td>amountchange</td>
<td>50083</td>
<td>-52.67</td>
<td>1267.10</td>
<td>-200412.13</td>
<td>-50.00</td>
<td>-30.00</td>
<td>-25.00</td>
<td>275.00</td>
</tr>
<tr class="even">
<td>hpa</td>
<td>50083</td>
<td>59.38</td>
<td>71.18</td>
<td>0.00</td>
<td>30.00</td>
<td>45.00</td>
<td>60.00</td>
<td>1000.00</td>
</tr>
<tr class="odd">
<td>freq</td>
<td>50083</td>
<td>8.04</td>
<td>11.39</td>
<td>0.00</td>
<td>2.00</td>
<td>4.00</td>
<td>10.00</td>
<td>218.00</td>
</tr>
<tr class="even">
<td>years</td>
<td>50082</td>
<td>6.10</td>
<td>5.50</td>
<td>0.00</td>
<td>2.00</td>
<td>5.00</td>
<td>9.00</td>
<td>95.00</td>
</tr>
<tr class="odd">
<td>mrm2</td>
<td>50082</td>
<td>13.01</td>
<td>12.08</td>
<td>0.00</td>
<td>4.00</td>
<td>8.00</td>
<td>19.00</td>
<td>168.00</td>
</tr>
<tr class="even">
<td>female</td>
<td>48972</td>
<td>0.28</td>
<td>0.45</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>1.00</td>
<td>1.00</td>
</tr>
<tr class="odd">
<td>couple</td>
<td>48935</td>
<td>0.09</td>
<td>0.29</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>1.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="callout callout-style-simple callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Demographics and State-Level Variables Summary
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Count</th>
<th>Mean</th>
<th>Std Dev</th>
<th>Min</th>
<th>25%</th>
<th>50%</th>
<th>75%</th>
<th>Max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nonlit</td>
<td>49631</td>
<td>2.47</td>
<td>1.96</td>
<td>0.00</td>
<td>1.00</td>
<td>3.00</td>
<td>4.00</td>
<td>6.00</td>
</tr>
<tr class="even">
<td>cases</td>
<td>49631</td>
<td>1.50</td>
<td>1.16</td>
<td>0.00</td>
<td>1.00</td>
<td>1.00</td>
<td>2.00</td>
<td>4.00</td>
</tr>
<tr class="odd">
<td>statecnt</td>
<td>50083</td>
<td>6.00</td>
<td>5.75</td>
<td>0.002</td>
<td>1.83</td>
<td>3.54</td>
<td>9.61</td>
<td>17.37</td>
</tr>
<tr class="even">
<td>stateresponse</td>
<td>50083</td>
<td>0.0206</td>
<td>0.0052</td>
<td>0.00</td>
<td>0.0182</td>
<td>0.0197</td>
<td>0.0230</td>
<td>0.0769</td>
</tr>
<tr class="odd">
<td>stateresponset</td>
<td>50083</td>
<td>0.0220</td>
<td>0.0063</td>
<td>0.00</td>
<td>0.0185</td>
<td>0.0217</td>
<td>0.0247</td>
<td>0.1111</td>
</tr>
<tr class="even">
<td>stateresponsec</td>
<td>50080</td>
<td>0.0177</td>
<td>0.0075</td>
<td>0.00</td>
<td>0.0129</td>
<td>0.0199</td>
<td>0.0208</td>
<td>0.0526</td>
</tr>
<tr class="odd">
<td>stateresponsetminc</td>
<td>50080</td>
<td>0.0043</td>
<td>0.0091</td>
<td>-0.0476</td>
<td>-0.0014</td>
<td>0.0018</td>
<td>0.0105</td>
<td>0.1111</td>
</tr>
<tr class="even">
<td>perbush</td>
<td>50048</td>
<td>0.488</td>
<td>0.079</td>
<td>0.0909</td>
<td>0.4444</td>
<td>0.4848</td>
<td>0.5253</td>
<td>0.7320</td>
</tr>
<tr class="odd">
<td>close25</td>
<td>50048</td>
<td>0.186</td>
<td>0.389</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>0.00</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>pwhite</td>
<td>48217</td>
<td>0.820</td>
<td>0.169</td>
<td>0.0094</td>
<td>0.756</td>
<td>0.873</td>
<td>0.939</td>
<td>1.00</td>
</tr>
<tr class="odd">
<td>pblack</td>
<td>48047</td>
<td>0.087</td>
<td>0.136</td>
<td>0.00</td>
<td>0.0147</td>
<td>0.0366</td>
<td>0.0909</td>
<td>0.9896</td>
</tr>
<tr class="even">
<td>page18_39</td>
<td>48217</td>
<td>0.322</td>
<td>0.103</td>
<td>0.00</td>
<td>0.2583</td>
<td>0.3055</td>
<td>0.3691</td>
<td>0.9975</td>
</tr>
<tr class="odd">
<td>ave_hh_sz</td>
<td>48221</td>
<td>2.43</td>
<td>0.38</td>
<td>0.00</td>
<td>2.21</td>
<td>2.44</td>
<td>2.66</td>
<td>5.27</td>
</tr>
<tr class="even">
<td>median_hhincome</td>
<td>48209</td>
<td>54815.70</td>
<td>22027.32</td>
<td>5000.00</td>
<td>39181.00</td>
<td>50673.00</td>
<td>66005.00</td>
<td>200001.00</td>
</tr>
<tr class="odd">
<td>powner</td>
<td>48214</td>
<td>0.669</td>
<td>0.193</td>
<td>0.00</td>
<td>0.560</td>
<td>0.712</td>
<td>0.817</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>psch_atlstba</td>
<td>48215</td>
<td>0.392</td>
<td>0.187</td>
<td>0.00</td>
<td>0.236</td>
<td>0.374</td>
<td>0.530</td>
<td>1.00</td>
</tr>
<tr class="odd">
<td>pop_propurban</td>
<td>48217</td>
<td>0.872</td>
<td>0.259</td>
<td>0.00</td>
<td>0.885</td>
<td>1.00</td>
<td>1.00</td>
<td>1.00</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>From the above tables we can infer that -</p>
<ul>
<li><p>Donation behavior is highly skewed: while the average donation (amount) is $0.92, the median is $0, indicating that most donors did not give during the campaign.</p></li>
<li><p>The maximum recorded donation is $400, and the standard deviation is 8.71, showing wide variability among those who did give. The previous highest donation (hpa) had a mean of $59.38, with values ranging from $0 to $1000.</p></li>
<li><p>Donor history shows that the average donor made 8 prior donations (freq), with some making over 200.</p></li>
<li><p>State-level response rates averaged 2.06% overall, with slightly higher response among treated individuals (2.20%) compared to control (1.77%).</p></li>
<li><p>Demographic indicators reveal:</p>
<ul>
<li><p>About 28% of donors were female, and 9% were couples.</p></li>
<li><p>The average median household income by zip code was around $54,816.</p></li>
<li><p>The average zip code was 82% white, 9% Black, and 87% urban.</p></li>
<li><p>About 39% of zip code residents had a bachelor’s degree or higher.</p></li>
</ul></li>
</ul>
</section>
<section id="balance-test" class="level3">
<h3 class="anchored" data-anchor-id="balance-test">Balance Test</h3>
<section id="t-statistic-test-on-multiple-variables-in-treatment-and-control-groups" class="level4">
<h4 class="anchored" data-anchor-id="t-statistic-test-on-multiple-variables-in-treatment-and-control-groups">T-statistic test on multiple variables in treatment and control groups</h4>
<p>As an ad hoc test of the randomization mechanism, I provide a series of tests that compare aspects of the treatment and control groups to assess whether they are statistically significantly different from one another. t-test is performed on a number of variables among the treatment and control group. the following code is used to perform the t-tests on different variables.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Split treatment and control</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>treatment_group <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amountchange'</span>].dropna()</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>control_group <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amountchange'</span>].dropna()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Means</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>mean_treat <span class="op">=</span> np.mean(treatment_group)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>mean_control <span class="op">=</span> np.mean(control_group)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Sizes</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>n_treat <span class="op">=</span> <span class="bu">len</span>(treatment_group)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>n_control <span class="op">=</span> <span class="bu">len</span>(control_group)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Variances</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>var_treat <span class="op">=</span> np.var(treatment_group, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>var_control <span class="op">=</span> np.var(control_group, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Manual t-statistic ---</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>numerator <span class="op">=</span> mean_treat <span class="op">-</span> mean_control</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>denominator <span class="op">=</span> np.sqrt((var_treat <span class="op">/</span> n_treat) <span class="op">+</span> (var_control <span class="op">/</span> n_control))</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>t_stat <span class="op">=</span> numerator <span class="op">/</span> denominator</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Degrees of Freedom ---</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>df_num <span class="op">=</span> (var_treat <span class="op">/</span> n_treat <span class="op">+</span> var_control <span class="op">/</span> n_control) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>df_den <span class="op">=</span> ((var_treat <span class="op">/</span> n_treat) <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> (n_treat <span class="op">-</span> <span class="dv">1</span>) <span class="op">+</span> ((var_control <span class="op">/</span> n_control) <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> (n_control <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df_num <span class="op">/</span> df_den</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Two-tailed p-value ---</span></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>p_value <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> t.sf(np.<span class="bu">abs</span>(t_stat), df)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"T-statistic: </span><span class="sc">{</span>t_stat<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Degrees of freedom: </span><span class="sc">{</span>df<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"P-value: </span><span class="sc">{</span>p_value<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Statistically significant at 95</span><span class="sc">% c</span><span class="st">onfidence level"</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Not statistically significant"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The following variables were tested (along with the t-test statistic):</p>
<ul>
<li><p>‘mrm2’ (number of months since last donation) - T-statistic: 0.1195 P-value: 0.9049. Inference: No statistically significant difference</p></li>
<li><p>‘freq’ (Number of prior donations) - T-statistic: -0.1108 P-value: 0.9117. Inference: No statistically significant difference</p></li>
<li><p>‘red0’ (Red state) - T-statistic: 1.8773 P-value: 0.0605. Inference - No statistically significant difference</p></li>
<li><p>‘blue0’ (Blue state) - T-statistic: -1.8773 P-value: 0.0605. Inference - No statistically significant difference</p></li>
<li><p>‘years’ (Number of years since initial donation) - T-statistic: -1.0909 P-value: 0.2753. Inference - No statistically significant difference</p></li>
<li><p>‘hpa’ (Highest previous contribution) - T-statistic: 0.9704 P-value: 0.3318. Inference: No statistically significant difference</p></li>
<li><p>‘psch_atlstba’ (Proportion who finished college within zip code) - T-statistic: -1.8427 P-value: 0.0654. Inference: No statistically significant difference</p></li>
<li><p>‘amountchange’ (Change in amount given) - T-statistic: 0.4713 P-value: 0.6374. Inference: No statistically significant difference</p></li>
</ul>
</section>
<section id="a-regression-analysis-on-amountchange" class="level4">
<h4 class="anchored" data-anchor-id="a-regression-analysis-on-amountchange">A regression analysis on ‘amountchange’</h4>
<p>A regression was conducted for ‘amountchange’ as dependent variable and ‘freq’, ‘years’, ‘hpa’,‘ask1’,‘ask2’,‘ask3’,‘mrm2’ as independent variable. Code shown below.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[[ <span class="st">'freq'</span>, <span class="st">'years'</span>, <span class="st">'hpa'</span>,<span class="st">'ask1'</span>,<span class="st">'ask2'</span>,<span class="st">'ask3'</span>,<span class="st">'mrm2'</span>]]</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'amountchange'</span>]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add constant (intercept)</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit linear regression model</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.OLS(y, X, missing<span class="op">=</span><span class="st">'drop'</span>).fit()</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Output results</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="table-1-linear-regression-output-amountchange" class="level6">
<h6 class="anchored" data-anchor-id="table-1-linear-regression-output-amountchange">Table 1: Linear Regression Output – amountchange</h6>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-Statistic</th>
<th>P-value</th>
<th>95% CI Lower</th>
<th>95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>const</td>
<td>-24.914</td>
<td>14.772</td>
<td>-1.687</td>
<td>0.092</td>
<td>-53.867</td>
<td>4.040</td>
</tr>
<tr class="even">
<td>freq</td>
<td>1.105</td>
<td>0.675</td>
<td>1.638</td>
<td>0.102</td>
<td>-0.218</td>
<td>2.427</td>
</tr>
<tr class="odd">
<td>years</td>
<td>-0.973</td>
<td>1.405</td>
<td>-0.693</td>
<td>0.489</td>
<td>-3.727</td>
<td>1.781</td>
</tr>
<tr class="even">
<td>hpa</td>
<td>-0.153</td>
<td>0.218</td>
<td>-0.703</td>
<td>0.482</td>
<td>-0.581</td>
<td>0.274</td>
</tr>
<tr class="odd">
<td>ask1</td>
<td>1.708</td>
<td>5.187</td>
<td>0.329</td>
<td>0.742</td>
<td>-8.458</td>
<td>11.874</td>
</tr>
<tr class="even">
<td>ask2</td>
<td>1.246</td>
<td>4.300</td>
<td>0.290</td>
<td>0.772</td>
<td>-7.183</td>
<td>9.674</td>
</tr>
<tr class="odd">
<td>ask3</td>
<td>-2.361</td>
<td>1.825</td>
<td>-1.294</td>
<td>0.196</td>
<td>-5.939</td>
<td>1.216</td>
</tr>
<tr class="even">
<td>mrm2</td>
<td>0.319</td>
<td>0.484</td>
<td>0.659</td>
<td>0.510</td>
<td>-0.629</td>
<td>1.267</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Observations</strong>: 50,082<br>
</li>
<li><strong>R-squared</strong>: 0.001<br>
</li>
<li><strong>Adjusted R-squared</strong>: 0.001<br>
]</li>
</ul>
<p>R-squared: 0.001 - Only 0.1% of the variation in amountchange is explained by the model — this is very low, which is expected in a clean RCT. All p-values &gt; 0.05 None of the pre-treatment variables are statistically significant predictors.</p>
<p>From the above tests (regression and t-test), we see that none of the tested variables show a statistically significant difference between the treatment and control groups. This supports the validity of the experiment as a randomized controlled trial (RCT), where treatment assignment is expected to be independent of observable characteristics.</p>
</section>
</section>
</section>
</section>
<section id="experimental-results" class="level2">
<h2 class="anchored" data-anchor-id="experimental-results">Experimental Results</h2>
<section id="charitable-contribution-made" class="level3">
<h3 class="anchored" data-anchor-id="charitable-contribution-made">Charitable Contribution Made</h3>
<p>First, I analyze whether matched donations lead to an increased response rate of making a donation. The following chart shows the proportion of Donors in Control and Treatment group.</p>
<section id="figure-1-proportion-of-donors-by-group" class="level6">
<h6 class="anchored" data-anchor-id="figure-1-proportion-of-donors-by-group">Figure 1: Proportion of Donors by Group</h6>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../files/Assignment1/proptc.png" class="img-fluid figure-img"></p>
<figcaption>Barplot comparing donation rates</figcaption>
</figure>
</div>
<p>A T-test on ‘gave’ yields the following statistical results -</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stat</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T-statistic</td>
<td>3.2095</td>
</tr>
<tr class="even">
<td>P-value</td>
<td>0.0013</td>
</tr>
</tbody>
</table>
<p>Statistically significant difference for ‘gave’ in treatment and control group (p &lt; 0.05).</p>
<p>Inference: There is a statistically significant difference in donation behavior between people who received the treatment (matching grant offer) and those who did not. From the bar plot above, we can say that people in the treatment group were more likely to donate, meaning the matching grant positively influenced giving behavior.</p>
</section>
<section id="table-2-probit-regression-output-probability-of-donation" class="level6">
<h6 class="anchored" data-anchor-id="table-2-probit-regression-output-probability-of-donation">Table 2: Probit Regression Output – Probability of Donation</h6>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 20%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Marginal Effect</th>
<th>Std. Error</th>
<th>z-value</th>
<th>P-value</th>
<th>95% CI Lower</th>
<th>95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>treatment</td>
<td>0.0043</td>
<td>0.001</td>
<td>3.104</td>
<td>0.002</td>
<td>0.002</td>
<td>0.007</td>
</tr>
</tbody>
</table>
<p>From the above results we observe that being in a treatment group has a p-value&lt; 0.05 and hence, offering a match (treating the donors) results in an increase in the likelihood of a donor donating any amount of money.</p>
<p><em>NOTE: Linear regression results appear replicate Table 3 column 1 in the paper. Probit results do not, despite Table 3 indicating its results come from probit regressions…</em></p>
</section>
</section>
<section id="differences-between-match-rates" class="level3">
<h3 class="anchored" data-anchor-id="differences-between-match-rates">Differences between Match Rates</h3>
<p>Next, I assess the effectiveness of different sizes of matched donations on the response rate.</p>
<p>A series of T-tests are performed to test whether the size of the match ratio has an effect on whether people donate or not. The following observations were recorded :</p>
<section id="table-3-t-test-results-for-match-ratio-comparisons" class="level4">
<h4 class="anchored" data-anchor-id="table-3-t-test-results-for-match-ratio-comparisons">Table 3: T-Test Results for Match Ratio Comparisons</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Test Comparison</th>
<th>t-statistic</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1:1 vs 2:1</td>
<td>-0.9650</td>
<td>0.3345</td>
</tr>
<tr class="even">
<td>1:1 vs 3:1</td>
<td>-1.0150</td>
<td>0.3101</td>
</tr>
<tr class="odd">
<td>2:1 vs 3:1</td>
<td>-0.0501</td>
<td>0.9600</td>
</tr>
</tbody>
</table>
<p>All the above tests have a very large P-value (p &gt; 0.05). This suggests that there is no significant statistical difference in the donation likelihood when different higher match ratios are offered which are in line with the author’s article on page 8.</p>
<p>A regression test to support the above argument is also conducted with match ratios as the independent variable and ‘gave’ as the dependent variable. The code below is used to regress ‘gave’ on match ratios code</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'file_path'</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Create dummy for ratio1 (1:1 match)</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'ratio1'</span>] <span class="op">=</span> np.where(df[<span class="st">'ratio'</span>] <span class="op">==</span> <span class="st">"1"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare features and outcome</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[[<span class="st">'ratio1'</span>, <span class="st">'ratio2'</span>, <span class="st">'ratio3'</span>]]</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'gave'</span>].astype(<span class="bu">int</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Add constant</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit OLS model</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.OLS(y, X, missing<span class="op">=</span><span class="st">'drop'</span>).fit()</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Show summary</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model.summary())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The results of the regression are tabulated further. #### Table 4: OLS Regression — Probability of Donation (<code>gave</code>)</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-Statistic</th>
<th>P-value</th>
<th>95% CI Lower</th>
<th>95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>const</td>
<td>0.0179</td>
<td>0.001</td>
<td>16.225</td>
<td>0.000</td>
<td>0.016</td>
<td>0.020</td>
</tr>
<tr class="even">
<td>ratio1</td>
<td>0.0029</td>
<td>0.002</td>
<td>1.661</td>
<td>0.097</td>
<td>-0.001</td>
<td>0.006</td>
</tr>
<tr class="odd">
<td>ratio2</td>
<td>0.0048</td>
<td>0.002</td>
<td>2.744</td>
<td>0.006</td>
<td>0.001</td>
<td>0.008</td>
</tr>
<tr class="even">
<td>ratio3</td>
<td>0.0049</td>
<td>0.002</td>
<td>2.802</td>
<td>0.005</td>
<td>0.001</td>
<td>0.008</td>
</tr>
</tbody>
</table>
<p>Again, it is observed from Table 4 that, none of the match ratio variables are statistically significant in influencing the likelihood of a donor making a donation. Both the T-tests and the Regression results support this argument.</p>
<p>The difference in average response rate between the 1:1 and 2:1 match ratios and the 2:1 and 3:1 ratios are calculated from the data collected. The values are shown in Table 5.2 The difference in average response rate between thecoeffecients of match ratios calculated using the regression (as seen in Table 4) estimated earlier turns out to be equal to those seen in Table 5.2 and Table 6.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate group-wise response rates from raw data</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>rate_1to1 <span class="op">=</span> df[df[<span class="st">'ratio1'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>rate_2to1 <span class="op">=</span> df[df[<span class="st">'ratio2'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>rate_3to1 <span class="op">=</span> df[df[<span class="st">'ratio3'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'gave'</span>].mean()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute differences</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>diff_2_vs_1 <span class="op">=</span> rate_2to1 <span class="op">-</span> rate_1to1</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>diff_3_vs_2 <span class="op">=</span> rate_3to1 <span class="op">-</span> rate_2to1</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>diff_3_vs_1 <span class="op">=</span> rate_3to1 <span class="op">-</span> rate_1to1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="table-5.1-response-rates-by-match-ratio-from-data" class="level4">
<h4 class="anchored" data-anchor-id="table-5.1-response-rates-by-match-ratio-from-data">Table 5.1: Response Rates by Match Ratio (From Data)</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Match Ratio</th>
<th>Response Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1:1</td>
<td>0.0207</td>
</tr>
<tr class="even">
<td>2:1</td>
<td>0.0226</td>
</tr>
<tr class="odd">
<td>3:1</td>
<td>0.0227</td>
</tr>
</tbody>
</table>
</section>
<section id="table-5.2-response-rate-differences-by-match-ratio-from-data" class="level4">
<h4 class="anchored" data-anchor-id="table-5.2-response-rate-differences-by-match-ratio-from-data">Table 5.2: Response Rate Differences by Match Ratio (From Data)</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Comparison</th>
<th>Response Rate Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2:1 vs 1:1</td>
<td>0.0019</td>
</tr>
<tr class="even">
<td>3:1 vs 2:1</td>
<td>0.0001</td>
</tr>
<tr class="odd">
<td>3:1 vs 1:1</td>
<td>0.0020</td>
</tr>
</tbody>
</table>
</section>
<section id="table-6-regression-coefficient-differences-by-match-ratio" class="level4">
<h4 class="anchored" data-anchor-id="table-6-regression-coefficient-differences-by-match-ratio">Table 6: Regression Coefficient Differences by Match Ratio</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Comparison</th>
<th>Regression Coefficient Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2:1 vs 1:1</td>
<td>0.0048 - 0.0029 = 0.0019</td>
</tr>
<tr class="even">
<td>3:1 vs 2:1</td>
<td>0.0049 - 0.0048 = 0.0001</td>
</tr>
<tr class="odd">
<td>3:1 vs 1:1</td>
<td>0.0049 - 0.0029 = 0.0020</td>
</tr>
</tbody>
</table>
<p>Both the raw data and the regression results show that increasing the match ratio has only a very small effect on the probability of donating. The increase from a 1:1 to a 2:1 match raises the response rate by just 0.19 percentage points, and from 2:1 to 3:1 by only 0.01 percentage points.This indicates that larger match ratios do not provide additional meaningful gains, consistent with the authors’ conclusion.</p>
</section>
</section>
<section id="size-of-charitable-contribution" class="level3">
<h3 class="anchored" data-anchor-id="size-of-charitable-contribution">Size of Charitable Contribution</h3>
<p>In this subsection, I analyze the effect of the size of matched donation on the size of the charitable contribution.</p>
<p>I performed a T-test on the ‘amount’ variable for treatment group.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> t</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Prepare data</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>treat_amt <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>][<span class="st">'amount'</span>].dropna()</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>control_amt <span class="op">=</span> df[df[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>][<span class="st">'amount'</span>].dropna()</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample sizes</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>n1 <span class="op">=</span> <span class="bu">len</span>(treat_amt)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>n0 <span class="op">=</span> <span class="bu">len</span>(control_amt)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Means</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>mean1 <span class="op">=</span> np.mean(treat_amt)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>mean0 <span class="op">=</span> np.mean(control_amt)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Variances (sample)</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>var1 <span class="op">=</span> np.var(treat_amt, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>var0 <span class="op">=</span> np.var(control_amt, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute t-statistic manually</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>numerator <span class="op">=</span> mean1 <span class="op">-</span> mean0</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>denominator <span class="op">=</span> np.sqrt((var1 <span class="op">/</span> n1) <span class="op">+</span> (var0 <span class="op">/</span> n0))</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>t_stat_manual <span class="op">=</span> numerator <span class="op">/</span> denominator</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Degrees of freedom </span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>df_num <span class="op">=</span> (var1 <span class="op">/</span> n1 <span class="op">+</span> var0 <span class="op">/</span> n0) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>df_den <span class="op">=</span> ((var1 <span class="op">/</span> n1) <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> (n1 <span class="op">-</span> <span class="dv">1</span>) <span class="op">+</span> ((var0 <span class="op">/</span> n0) <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> (n0 <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>dof <span class="op">=</span> df_num <span class="op">/</span> df_den</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute p-value (two-sided)</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>p_val_manual <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> t.sf(np.<span class="bu">abs</span>(t_stat_manual), dof)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The t-statistic was 1.9183 and the p-value was 0.0551, which is slightly above the conventional 5% significance level. This indicates that the difference in average donation amount between the treatment and control groups is not statistically significant at the standard threshold. While the result suggests that receiving a matching grant letter might increase donation amounts, the evidence is not strong enough to confirm a significant effect.</p>
<p>To analyze the effect of treatment on donation amount conditional on donating, I ran a bivariate OLS regression restricted to individuals with positive donation amounts (amount &gt; 0). The tabulated in Table 7. The intercept indicates that control group donors donated an average of $45.54, while treated donors donated $1.67 less on average. However, this difference is not statistically significant since the p value = 0.561). Since the model conditions on having donated, the treatment effect here does not have a causal interpretation, and reflects only differences among those already inclined to give.</p>
<section id="table-7-ols-regression-donation-amount-only-donors" class="level4">
<h4 class="anchored" data-anchor-id="table-7-ols-regression-donation-amount-only-donors">Table 7: OLS Regression — Donation Amount (Only Donors)</h4>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Coefficient</th>
<th>Std. Error</th>
<th>t-Statistic</th>
<th>P-value</th>
<th>95% CI Lower</th>
<th>95% CI Upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>const</td>
<td>45.5403</td>
<td>2.423</td>
<td>18.792</td>
<td>0.000</td>
<td>40.785</td>
<td>50.296</td>
</tr>
<tr class="even">
<td>treatment</td>
<td>–1.6684</td>
<td>2.872</td>
<td>–0.581</td>
<td>0.561</td>
<td>–7.305</td>
<td>3.968</td>
</tr>
</tbody>
</table>
<ul>
<li><strong>Number of observations</strong>: 1,034<br>
</li>
<li><strong>R-squared</strong>: 0.000<br>
</li>
<li><strong>F-statistic</strong>: 0.3374 (p = 0.561)<br>
</li>
<li><strong>Dependent variable</strong>: <code>amount</code> (only where amount &gt; 0)</li>
</ul>
<p>We plot histograms for the treatment group and one for the control donation amounts only among people who donated. The code below is used to generate these plots. The plot obtain is seen below in Figure 2.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: donation-histograms</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Histogram of Donation Amounts for Treatment and Control Groups (Donors Only)"</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-subcap: ["Treatment Group", "Control Group"]</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#| layout-ncol: 2</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter to donors only</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>donors <span class="op">=</span> df[df[<span class="st">'amount'</span>] <span class="op">&gt;</span> <span class="dv">0</span>].copy()</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Split by group</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>treat_donors <span class="op">=</span> donors[donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">1</span>]</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>control_donors <span class="op">=</span> donors[donors[<span class="st">'treatment'</span>] <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate means</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>mean_treat <span class="op">=</span> treat_donors[<span class="st">'amount'</span>].mean()</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>mean_control <span class="op">=</span> control_donors[<span class="st">'amount'</span>].mean()</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Create subplots</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">5</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"Histogram of Donation Amounts for Treatment and Control Groups (Donors Only)"</span>, fontsize<span class="op">=</span><span class="dv">16</span>)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Treatment histogram</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>sns.histplot(treat_donors[<span class="st">'amount'</span>], bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>], color<span class="op">=</span><span class="st">'skyblue'</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].axvline(mean_treat, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f'Mean = </span><span class="sc">{</span>mean_treat<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Treatment Group"</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"Donation Amount"</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"Frequency"</span>)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend()</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Control histogram</span></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>sns.histplot(control_donors[<span class="st">'amount'</span>], bins<span class="op">=</span><span class="dv">30</span>, ax<span class="op">=</span>axes[<span class="dv">1</span>], color<span class="op">=</span><span class="st">'lightgreen'</span>)</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axvline(mean_control, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="ss">f'Mean = </span><span class="sc">{</span>mean_control<span class="sc">:.2f}</span><span class="ss">'</span>)</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Control Group"</span>)</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"Donation Amount"</span>)</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend()</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="figure-2-histogram-of-dantion-amounts-for-treatment-and-control-groups" class="level6">
<h6 class="anchored" data-anchor-id="figure-2-histogram-of-dantion-amounts-for-treatment-and-control-groups">Figure 2: Histogram of Dantion Amounts for Treatment and Control Groups</h6>
<p><img src="../../files/Assignment1/donors_mean.png" class="img-fluid" alt="Barplot comparing donation rates"> Both groups have a highly right-skewed distribution — most donors give smaller amounts, but a few give much more. The average donation in the control group is slightly higher than in the treatment group. This matches your earlier OLS regression result: The treatment group gave $1.67 less on average (not statistically significant).</p>
</section>
</section>
</section>
</section>
<section id="simulation-experiment" class="level2">
<h2 class="anchored" data-anchor-id="simulation-experiment">Simulation Experiment</h2>
<p>As a reminder of how the t-statistic “works,” in this section I use simulation to demonstrate the Law of Large Numbers and the Central Limit Theorem.</p>
<p>Suppose the true distribution of respondents who do not get a charitable donation match is Bernoulli with probability p=0.018 that a donation is made.</p>
<p>Further suppose that the true distribution of respondents who do get a charitable donation match of any size is Bernoulli with probability p=0.022 that a donation is made.</p>
<section id="law-of-large-numbers" class="level3">
<h3 class="anchored" data-anchor-id="law-of-large-numbers">Law of Large Numbers</h3>
<p><em>to do: Simulate 10,000 draws from the control distribution and 10,000 draws from the treatment distribution. You’ll then calculate a vector of 10,000 differences, and then you’ll plot the cumulative average of that vector of differences. This average will likely be “noisey” when only averaging a few numbers, but should “settle down” and approximate the treatment effect (0.004 = 0.022 - 0.018) as the sample size gets large. Explain the chart to the reader.</em></p>
<p>I simulate 10,000 draws from the control distribution and 10,000 draws from the treatment distribution and further calculate a vector of 10,000 differences. This simulation in conducted using the code below</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate 10,000 binary draws</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>control <span class="op">=</span> np.random.binomial(n<span class="op">=</span><span class="dv">1</span>, p<span class="op">=</span><span class="fl">0.018</span>, size<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>treatment <span class="op">=</span> np.random.binomial(n<span class="op">=</span><span class="dv">1</span>, p<span class="op">=</span><span class="fl">0.022</span>, size<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute difference in outcomes</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>differences <span class="op">=</span> treatment <span class="op">-</span> control</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute cumulative average</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>cumulative_avg <span class="op">=</span> np.cumsum(differences) <span class="op">/</span> np.arange(<span class="dv">1</span>, <span class="bu">len</span>(differences) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>))</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>plt.plot(cumulative_avg, color<span class="op">=</span><span class="st">'purple'</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>plt.axhline(<span class="fl">0.004</span>, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'True Treatment Effect = 0.004'</span>)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Cumulative Average of Simulated Differences Between Treatment and Control"</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Number of Simulations"</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"Cumulative Average Difference"</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="figure-3-cumulative-average-of-simulated-differences-between-treatment-and-control" class="level6">
<h6 class="anchored" data-anchor-id="figure-3-cumulative-average-of-simulated-differences-between-treatment-and-control">Figure 3: Cumulative Average of Simulated Differences Between Treatment and Control</h6>
<p><img src="../../files/Assignment1/Sim1.png" class="img-fluid" alt="Cumulative Avg difference in C &amp; T"> The chart above demonstrates the <strong>Law of Large Numbers (LLN)</strong> using simulated binary outcomes from a Bernoulli distribution. In this simulation:</p>
<ul>
<li>Control group donations were drawn with probability <strong>p = 0.018</strong></li>
<li>Treatment group donations were drawn with <strong>p = 0.022</strong></li>
</ul>
<p>The cumulative difference in donation behavior between the groups was tracked across 10,000 simulations. While the average difference fluctuates at first due to randomness, it gradually <strong>settles near 0.004</strong>, the true treatment effect. This convergence illustrates the Law of Large Numbers: as the sample size increases, the sample average approaches the true population average.</p>
</section>
</section>
<section id="central-limit-theorem" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem">Central Limit Theorem</h3>
<p><em>to do: Make 4 histograms at sample sizes 50, 200, 500, and 1000. To do this for a sample size of e.g.&nbsp;50, take 50 draws from each of the control and treatment distributions, and calculate the average difference between those draws. Then repeat that process 999 more times so that you have 1000 averages. Plot the histogram of those averages. The repeat for the other 3 histograms. Explain this sequence of histograms and its relationship to the central limit theorem to the reader.</em></p>
</section>
<section id="central-limit-theorem-simulation" class="level3">
<h3 class="anchored" data-anchor-id="central-limit-theorem-simulation">Central Limit Theorem: Simulation</h3>
<p>The sequence of histograms below in Figure 4 illustrates the Central Limit Theorem (CLT). Each plot shows the distribution of the difference in sample means between a treatment group (<code>p = 0.022</code>) and a control group (<code>p = 0.018</code>) based on 1000 simulations for different sample sizes.</p>
<p>As the sample size increases: - The distribution of the average differences becomes more symmetric and bell-shaped - The sampling distribution centers around the true treatment effect (0.004) - The variability (spread) decreases</p>
<p>This demonstrates the CLT: as sample size increases, the sampling distribution of the sample mean approaches a normal distribution, regardless of the original (Bernoulli) distribution of the data. The code for simulation is given below.</p>
<section id="figure-4-central-limit-theorem---simulation" class="level6">
<h6 class="anchored" data-anchor-id="figure-4-central-limit-theorem---simulation">Figure 4: Central Limit Theorem - Simulation</h6>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../files/Assignment1/CLT.png" class="img-fluid figure-img"></p>
<figcaption>Central Limit Theorem - Simulation</figcaption>
</figure>
</div>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Settings</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">50</span>, <span class="dv">200</span>, <span class="dv">500</span>, <span class="dv">1000</span>]</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>simulations <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>true_diff <span class="op">=</span> <span class="fl">0.022</span> <span class="op">-</span> <span class="fl">0.018</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Create 4 subplots</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">8</span>))</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> idx, n <span class="kw">in</span> <span class="bu">enumerate</span>(sample_sizes):</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    diffs <span class="op">=</span> []</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(simulations):</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>        control <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.018</span>, size<span class="op">=</span>n)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>        treatment <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.022</span>, size<span class="op">=</span>n)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>        diff <span class="op">=</span> np.mean(treatment) <span class="op">-</span> np.mean(control)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>        diffs.append(diff)</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> axes[idx <span class="op">//</span> <span class="dv">2</span>][idx <span class="op">%</span> <span class="dv">2</span>]</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    sns.histplot(diffs, bins<span class="op">=</span><span class="dv">30</span>, kde<span class="op">=</span><span class="va">True</span>, ax<span class="op">=</span>ax, color<span class="op">=</span><span class="st">'lightblue'</span>)</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    ax.axvline(true_diff, color<span class="op">=</span><span class="st">'red'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>, label<span class="op">=</span><span class="st">'True Treatment Effect = 0.004'</span>)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"Sample Size = </span><span class="sc">{</span>n<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Difference in Means"</span>)</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>    ax.legend()</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>